# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import message_pb2 as message__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendInit = channel.unary_unary(
                '/server.GameService/SendInit',
                request_serializer=message__pb2._InitRequest.SerializeToString,
                response_deserializer=message__pb2._InitResponse.FromString,
                _registered_method=True)
        self.SendInitPolicy = channel.unary_unary(
                '/server.GameService/SendInitPolicy',
                request_serializer=message__pb2._InitPolicyRequest.SerializeToString,
                response_deserializer=message__pb2._InitPolicyResponse.FromString,
                _registered_method=True)
        self.SendAction = channel.unary_unary(
                '/server.GameService/SendAction',
                request_serializer=message__pb2._actionSet.SerializeToString,
                response_deserializer=message__pb2._actionResponse.FromString,
                _registered_method=True)
        self.BroadcastGameState = channel.unary_stream(
                '/server.GameService/BroadcastGameState',
                request_serializer=message__pb2._GameStateRequest.SerializeToString,
                response_deserializer=message__pb2._GameStateResponse.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendInitPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastGameState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendInit': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInit,
                    request_deserializer=message__pb2._InitRequest.FromString,
                    response_serializer=message__pb2._InitResponse.SerializeToString,
            ),
            'SendInitPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInitPolicy,
                    request_deserializer=message__pb2._InitPolicyRequest.FromString,
                    response_serializer=message__pb2._InitPolicyResponse.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=message__pb2._actionSet.FromString,
                    response_serializer=message__pb2._actionResponse.SerializeToString,
            ),
            'BroadcastGameState': grpc.unary_stream_rpc_method_handler(
                    servicer.BroadcastGameState,
                    request_deserializer=message__pb2._GameStateRequest.FromString,
                    response_serializer=message__pb2._GameStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('server.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server.GameService/SendInit',
            message__pb2._InitRequest.SerializeToString,
            message__pb2._InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendInitPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server.GameService/SendInitPolicy',
            message__pb2._InitPolicyRequest.SerializeToString,
            message__pb2._InitPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server.GameService/SendAction',
            message__pb2._actionSet.SerializeToString,
            message__pb2._actionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/server.GameService/BroadcastGameState',
            message__pb2._GameStateRequest.SerializeToString,
            message__pb2._GameStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
