version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "50051:50051"
    command: ["--urls", "http://0.0.0.0:50051"]
    networks:
      - game-network
    tty: true

  client1:
    build:
      context: ./client/client_gRPC
      dockerfile: Dockerfile
    depends_on:
      - server
    command: ["--host", "server", "--port", "50051", "--mode", "remote", "--strategy", "mcts"]
    networks:
      - game-network
    environment:
      - PYTHONUNBUFFERED=1
    tty: true

  client2:
    build:
      context: ./client/client_gRPC
      dockerfile: Dockerfile
    depends_on:
      - server
    command: ["--host", "server", "--port", "50051", "--mode", "remote", "--strategy", "aggressive"]
    networks:
      - game-network
    environment:
      - PYTHONUNBUFFERED=1
    tty: true

networks:
  game-network:
    driver: bridge 